{{- if .Values.ingress.enabled -}}
{{- $fullName := include "single-container.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "single-container.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.ingressClassname }}
  ingressClassName: {{ .Values.ingress.ingressClassname }}
  {{- end}}
  {{- if .Values.ingress.ingressClass }}
  ingressClass: {{ .Values.ingress.ingressClass }}
  {{- end}}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- range $.Values.ingress.hosts }}
        - {{ .host | quote }}
        {{- end }}
      secretName: {{ include "single-container.tlssecretname" . }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- else }}
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
  {{- end }}
